### ISSUE TITLE
bug found in prediction file

### ISSUE THREAD

**Issue by Lijiachen1018** [yulingtianxia/AudioEmotion#2]
One line is missing after line 53, which causes `RuntimeError: Column name deep_features does not exist`.
https://github.com/yulingtianxia/AudioEmotion/blob/a6aa7a783602c9a04b23ddc3f2178655c051a6fa/Source/turicreate_classifier.py#L53

add the following line between line 53 and 54 in file `Source/turicreate_classifier.py`
```python
data['deep_features'] = tc.sound_classifier.get_deep_features(data['audio'])
```

**Comment by yulingtianxia** [comment]
Thanks for your suggestion! Would you like to send a PR to me?

**Comment by Lijiachen1018** [comment]
> Thanks for your suggestion! Would you like to send a PR to me?

Hi I have opened a pull request #3
